export const ROUTES = {
  HOME: "/",
  SAVE_RECIPES: "/save-recipes",
  CREATE_RECIPE: "/create-recipe",
  EDIT_RECIPE: "/edit-recipe",
  LOGIN: "/login",
  REGISTER: "/register",
  PROFILE: "/profile",
  EDIT_PROFILE: "edit-profile",
  EDIT_RECIPES: "edit-recipes",
  RECIPE_CARD: "recipe-card",
  USER: `/user`,
  MEAT: `meat`,
  DAIRY: `dairy`,
  PARVE: `parve`,
  ALL_RECIPES: "all-recipes",
  RECIPES: `/recipes`,
};
